version: '0.0.0.{build}'
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
  - ps: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest "https://raw.githubusercontent.com/vostok/appveyor/master/build.ps1" -OutFile "$env:appveyor_build_folder/build.ps1"
  - powershell -File .\build.ps1
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/f02e74a3a636a56c590b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
deploy:
  - provider: Environment
    name: Nuget
    on:
      appveyor_repo_tag: true
    artifact: /.*\.nupkg/
  - provider: Environment
    name: FullNuget
    artifact: /.*\.nupkg/
